import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NavigationBar from "@/components/navigation-bar";
import { cn } from "@/lib/utils";
import Providers from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Providers>
        <html lang="en">
          <body
            className={cn(inter.className, "min-h-screen flex flex-col p-4")}
          >
            <NavigationBar />
            <div className="flex-1">{children}</div>
          </body>
        </html>
      </Providers>
    </ClerkProvider>
  );
}
