import type { Metadata } from "next";
import "@/app/globals.css";
import Providers from "@/components/providers";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Providers>
        <html lang="en">
          <body>{children}</body>
        </html>
      </Providers>
    </ClerkProvider>
  );
}
