import type { Metadata } from 'next'
import '@/app/globals.css'
import { inter } from '@/lib/fonts'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Logbook',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'min-h-screen h-screen')}>
        {children}
      </body>
    </html>
  )
}
