import type { Metadata } from 'next'
import '@/app/globals.css'
import NavigationBar from '@/components/nav/navigation-bar'
import Footer from '@/components/footer/footer'

export const metadata: Metadata = {
  title: 'Logbook',
  description: 'Generated by create next app',
}

type LayoutProps = Readonly<{
  children: React.ReactNode
  today: React.ReactNode
}>


export default function RootLayout({ children, today, }: LayoutProps) {
  return (
    <div className="flex flex-col min-h-screen w-full p-4">
      <NavigationBar />
      <div className="flex-1 max-w-screen-lg h-full w-full m-auto py-8 flex flex-col gap-10">
        {children}
        {today}
      </div>
      <Footer />
    </div>
  )
}
